Python入门
---------------

- 正确地在您的系统上安装 Python

.. toctree::
    :maxdepth: 1

    starting/win
    starting/linux
    starting/pip

Python 开发环境
---------------------------

这部分指南关注 Python 开发环境，以及用于编写 Python 代码的可用且最实用的工具。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/venv


写出优雅的Python代码
--------------------------------

这部分指南关注编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 4

   writing/structure
   writing/style
   writing/reading
   writing/typing
   writing/documentation
   writing/tests
   writing/logging

掌握Python
------------------------------------

.. toctree::
   :maxdepth: 2

   Python进阶/index

最佳实践
-------------------------------------

Python养成周期的第三阶段阶段，有两个方向并行进行

* 通用组件代码库的积累
* 设计模式的总结

完成后，达成Python开发者养成周期的90%进度，大幅度提高开发效率

.. toctree::
   :maxdepth: 2

   项目工具/index
   组件/index
   faq
   demos/numpy-style
   知识点
   awesome/index








