Python入门
---------------

- 正确地在您的系统上安装 Python

.. toctree::
    :maxdepth: 1

    starting/win
    starting/linux
    starting/pip

Python 开发环境
---------------------------

这部分指南关注 Python 开发环境，以及用于编写 Python 代码的可用且最实用的工具。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/venv


写出优雅的Python代码
--------------------------------

这部分指南关注编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 4

   writing/structure
   writing/style
   writing/reading
   writing/typing
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas

项目工具
-------------------------------------

写代码只是软件工程的一小部分，还需要掌握自动化部署和测试、编写项目文档等。
以下工具便是提供这样的功能，也适合于其他语言入go和Node.js使用。

.. toctree::
   :maxdepth: 2

   项目工具/index

最佳实践
-------------------------------------

知识点归纳，代码库整理

.. toctree::
   :maxdepth: 2

   最佳实践/组件/index
   最佳实践/faq
   最佳实践/demos/numpy-style
   最佳实践/知识点
   最佳实践/awesome/index








