Python入门
---------------

- 正确地在您的系统上安装 Python

.. toctree::
    :maxdepth: 1

    starting/win
    starting/linux
    starting/pip

Python 开发环境
---------------------------

这部分指南关注 Python 开发环境，以及用于编写 Python 代码的可用且最实用的工具。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/venv


写出优雅的Python代码
--------------------------------

这部分指南关注编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 4

   writing/structure
   writing/style
   writing/reading
   writing/typing
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license


部署优雅的Python代码
--------------------------------

这部分指南关注分享和部署您的Python代码。

.. toctree::
   :maxdepth: 2

   shipping/publishing
   shipping/packaging
   shipping/freezing

归纳整理和最佳实践
-------------------------------------

知识点归纳，代码库整理

.. toctree::
   :maxdepth: 2

   最佳实践/组件/index
   最佳实践/faq
   最佳实践/demos/numpy-style
   最佳实践/知识点
   最佳实践/awesome/index








